services:
  db:
    image: postgres:latest
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: crusader
    volumes:
      - "pgdata:/var/lib/postgresql"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  pgdata: {}
