//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerJwtScopes = "BearerJwt.Scopes"
)

// Member Representation of a member
type Member struct {
	CreatedAt      *time.Time     `json:"created_at,omitempty"`
	DiscordId      string         `json:"discordId"`
	DiscordNick    string         `json:"discordNick"`
	MembershipType MembershipType `json:"membershipType"`
	Name           string         `json:"name"`
	Points         *float32       `json:"points,omitempty"`
	Rank           *Rank          `json:"rank,omitempty"`
	Stab           *[]Stab        `json:"stab,omitempty"`
	SteamId        string         `json:"steamId"`
	UnitRole       *UnitRole      `json:"unitRole,omitempty"`
	UpdatedAt      *time.Time     `json:"updated_at,omitempty"`
}

// MemberCreate Representation of a member creation
type MemberCreate struct {
	DiscordId        string   `json:"discordId"`
	DiscordNick      string   `json:"discordNick"`
	MembershipTypeId int      `json:"membershipTypeId"`
	Name             string   `json:"name"`
	Points           *float32 `json:"points,omitempty"`
	RankLevel        *int     `json:"rankLevel,omitempty"`
	StabIds          *[]int   `json:"stabIds,omitempty"`
	SteamId          string   `json:"steamId"`
	UnitRoleId       *int     `json:"unitRoleId,omitempty"`
}

// MemberPartialUpdate Representation of a partial member update
type MemberPartialUpdate struct {
	DiscordId        *string  `json:"discordId,omitempty"`
	DiscordNick      *string  `json:"discordNick,omitempty"`
	MembershipTypeId *int     `json:"membershipTypeId,omitempty"`
	Name             *string  `json:"name,omitempty"`
	Points           *float32 `json:"points,omitempty"`
	RankLevel        *int     `json:"rankLevel,omitempty"`
	StabIds          *[]int   `json:"stabIds,omitempty"`
	SteamId          *string  `json:"steamId,omitempty"`
	UnitRoleId       *int     `json:"unitRoleId,omitempty"`
}

// MemberUpdate Representation of a member update
type MemberUpdate struct {
	DiscordId        string  `json:"discordId"`
	DiscordNick      string  `json:"discordNick"`
	MembershipTypeId int     `json:"membershipTypeId"`
	Name             string  `json:"name"`
	Points           float32 `json:"points"`
	RankLevel        int     `json:"rankLevel"`
	StabIds          []int   `json:"stabIds"`
	SteamId          string  `json:"steamId"`
	UnitRoleId       *int    `json:"unitRoleId,omitempty"`
}

// MembershipType defines model for Membership_Type.
type MembershipType struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Rank defines model for Rank.
type Rank struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Level     *int       `json:"level,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Stab defines model for Stab.
type Stab struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int       `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// UnitRole defines model for UnitRole.
type UnitRole struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int       `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Unit        *Stab      `json:"unit,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// Id defines model for id.
type Id = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Errors *[]struct {
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Message string `json:"message"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Message string `json:"message"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message string `json:"message"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message string `json:"message"`
}

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = MemberCreate

// PartialUpdateMemberJSONRequestBody defines body for PartialUpdateMember for application/json ContentType.
type PartialUpdateMemberJSONRequestBody = MemberPartialUpdate

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = MemberUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create member
	// (POST /member)
	CreateMember(w http.ResponseWriter, r *http.Request)
	// Delete member
	// (DELETE /member/{id})
	RemoveMember(w http.ResponseWriter, r *http.Request, id Id)
	// Get member
	// (GET /member/{id})
	GetMember(w http.ResponseWriter, r *http.Request, id Id)
	// Patch member
	// (PATCH /member/{id})
	PartialUpdateMember(w http.ResponseWriter, r *http.Request, id Id)
	// Update member
	// (PUT /member/{id})
	UpdateMember(w http.ResponseWriter, r *http.Request, id Id)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PartialUpdateMember operation middleware
func (siw *ServerInterfaceWrapper) PartialUpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PartialUpdateMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/member", wrapper.CreateMember)
	m.HandleFunc("DELETE "+options.BaseURL+"/member/{id}", wrapper.RemoveMember)
	m.HandleFunc("GET "+options.BaseURL+"/member/{id}", wrapper.GetMember)
	m.HandleFunc("PATCH "+options.BaseURL+"/member/{id}", wrapper.PartialUpdateMember)
	m.HandleFunc("PUT "+options.BaseURL+"/member/{id}", wrapper.UpdateMember)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7buBJ+FYLnXOxiVVtO0qL1XZptixRNt8gP9iIICkYcR2wkkh2OnBiB32bfZF9s",
	"QUqWLNu1nSZxjaK5CCJ5ZjjzzcfhcJw7npjcGg2aHO/fcStQ5ECA4UlJ/1uCS1BZUkbzPpfKJQblZyXZ",
	"bxZVLnDErmHEzIAJlkN+Cfg7j7jyslZQyiOuRQ68761FHOFroRAk7xMWEHGXpJALvwyNrJdyhEpf8fF4",
	"7IWdNdpBcOa1kMfwtQBH/ikxmkCHP4W1mUqE96/7xXkn76bMWjQWkFRpBBBNFRtB7uYFcnBOXMEih6LJ",
	"G3P5BRLizQuBKEb+eal2E/p5LXgxZ9RLthE/TYE5wCEgS0yRSaYNsUJLQEdCS0YpMCyRYbIARoYpPRSZ",
	"ksyNNInbjnftwOhBppKHgPdk0U28b8K7BOaJmQGBnAQlWFLFwG4UpSHupEAETcyRIPAcLMFwpsAEQtyH",
	"mgC1yE4Cgm98/rcRgirBoBNTeI9BMqFZoeHWQuJBSIyWyiswSgUxizAE7T9QxAZocjYosoHKMqWvphkR",
	"MPho6K0ptNziwBOhfd4Hqk1okNPZHE/qRXDpKBSb+Qp1DBbBgaYQ2XRh4tFMVAmCIJCfRcADboWnHO/z",
	"nXjn+bNe71m8x3Z2+ruv+ntxJ37Re9Hb/SOOecQHBnOvw6UgeEYqBx7N4hJNSuWhbBuPe83PErWPKrlu",
	"Kx6JW/YahdKLtMoIXarsafjojv8fYcD7/H/dpsR3K/i6R7X05yA+nlTpmfUWrWSNqk6LWrQXx7WgLgLU",
	"nhZCX69y5NjL+LySuGyV5WVKJ154Qfl1BCKfhXt/BdyFVnRsspWQnU3kvI6VT8abmf0U0jKX3ibWaZq1",
	"uXOx4MAq834QaH+fncPCTvFSs1voB5J8Zs1eraA0wVXJwadh9QcYQrZ6cU/qQ9luN5ZrPCqjV+OzDtcC",
	"rx7Ctk8CSYnsLOyZ9UhnS5UJ+crt9ot6Pxn1vsGX+xDlF0F+1aYm6CaqGrOHla6mQZpriJ+2dVTfRZ99",
	"ffPvP0ih0Z1H/ml7ljkEj6vub5OwZetxfx65dzBAUFuC3EnVC2/0rjJdaqfNn0KSauWbYLYvc6WVI5x0",
	"go9E25MX24D62dQ9YCuQf1voa2K5Inb618Hjoe3NfoPnWtG6V6/NZsefNpAUqGh04h2pJoIgEPD9TXDh",
	"Mjy8nZh///cpr6YF3lD5abNUSmTLiYTSAzPfa7wpA2I3Bq+dFUnwUlEI8QALJyQg2/90yCM+BHSlUtyJ",
	"Oz0PjrGghVW8z3c7cWfXn0aC0uBzN6+nFtaUo8z2yuXdzDHBNNwwBH9KhcHWyAIrT6UOD0uU29AfpJXS",
	"0WTIUQ1PXhs5utfIZ/XEoLo5jtunM2EBs+Panbj3yGuvmh7eCMdckSTg3KDIIia0rFEsR0hBpNrNYTC2",
	"F8ffWrsOpjs1eA4qr1ar1MPWccSfr7PGoinlNOt5/7zF9/OL8UXEXZHnAkc1AZoxF4krV07jwosLb6ui",
	"XvdOyXHJuwwW9dl/hveegWuy7xhyM2zYN/0dwvniwBuRrpLchzLDnb15t5al+rIgRikgMOWYNqxiHSPD",
	"EKhA/f3Z3lutUo9XN5XtMkNLsh3xK6BFNyiPxT0y+w7oUdMab6AknNS8yEY++6hgCOVQOa/C/Jm48A5o",
	"KRGsoCSdp0I1lMlG1d35HqRozXMeSo+nOqjaQ6e1zquNkzOk5iem5icf33JyFguq1Nl9CbndTNxqClZt",
	"/I+g4HY2UmW2ljVSwZg3XtKrDe4Hk4iMSRhCZmwevpkOsjziBWbVxaPf7WZeLjWO+i/jl3FgYLXSrMUy",
	"kQwhC4mqme+af6yofBtfjP8LAAD//2q9xF/PIQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
