//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerJwtScopes = "BearerJwt.Scopes"
)

// Member Representation of a member
type Member struct {
	CreatedAt      string   `json:"created_at"`
	DiscordId      string   `json:"discord_id"`
	DiscordNick    string   `json:"discord_nick"`
	MembershipType string   `json:"membership_type"`
	Name           string   `json:"name"`
	Points         string   `json:"points"`
	Rank           string   `json:"rank"`
	Stab           []string `json:"stab"`
	SteamId        string   `json:"steam_id"`
	Unit           string   `json:"unit"`
	UpdatedAt      string   `json:"updated_at"`
}

// MemberCreate defines model for MemberCreate.
type MemberCreate struct {
	DiscordId      string `json:"discord_id"`
	DiscordNick    string `json:"discord_nick"`
	MembershipType int    `json:"membership_type"`
	Name           string `json:"name"`
	Points         int    `json:"points"`
	Rank           *int   `json:"rank,omitempty"`
	Stab           *int   `json:"stab,omitempty"`
	SteamId        string `json:"steam_id"`
	Unit           *int   `json:"unit,omitempty"`
}

// MemberPartialUpdate defines model for MemberPartialUpdate.
type MemberPartialUpdate struct {
	DiscordId      *string   `json:"discord_id,omitempty"`
	DiscordNick    *string   `json:"discord_nick,omitempty"`
	MembershipType *string   `json:"membership_type,omitempty"`
	Name           *string   `json:"name,omitempty"`
	Points         *string   `json:"points,omitempty"`
	Rank           *string   `json:"rank,omitempty"`
	Stab           *[]string `json:"stab,omitempty"`
	SteamId        *string   `json:"steam_id,omitempty"`
	Unit           *string   `json:"unit,omitempty"`
}

// MemberUpdate defines model for MemberUpdate.
type MemberUpdate struct {
	DiscordId      string   `json:"discord_id"`
	DiscordNick    string   `json:"discord_nick"`
	MembershipType string   `json:"membership_type"`
	Name           string   `json:"name"`
	Points         string   `json:"points"`
	Rank           string   `json:"rank"`
	Stab           []string `json:"stab"`
	SteamId        string   `json:"steam_id"`
	Unit           string   `json:"unit"`
}

// Id defines model for id.
type Id = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Errors *[]struct {
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Message string `json:"message"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Message string `json:"message"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message string `json:"message"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message string `json:"message"`
}

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = MemberCreate

// PartialUpdateMemberJSONRequestBody defines body for PartialUpdateMember for application/json ContentType.
type PartialUpdateMemberJSONRequestBody = MemberPartialUpdate

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = MemberUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create member
	// (POST /member)
	CreateMember(w http.ResponseWriter, r *http.Request)
	// Delete member
	// (DELETE /member/{id})
	RemoveMember(w http.ResponseWriter, r *http.Request, id Id)
	// Get member
	// (GET /member/{id})
	GetMember(w http.ResponseWriter, r *http.Request, id Id)
	// Patch member
	// (PATCH /member/{id})
	PartialUpdateMember(w http.ResponseWriter, r *http.Request, id Id)
	// Update member
	// (PUT /member/{id})
	UpdateMember(w http.ResponseWriter, r *http.Request, id Id)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PartialUpdateMember operation middleware
func (siw *ServerInterfaceWrapper) PartialUpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PartialUpdateMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/member", wrapper.CreateMember)
	m.HandleFunc("DELETE "+options.BaseURL+"/member/{id}", wrapper.RemoveMember)
	m.HandleFunc("GET "+options.BaseURL+"/member/{id}", wrapper.GetMember)
	m.HandleFunc("PATCH "+options.BaseURL+"/member/{id}", wrapper.PartialUpdateMember)
	m.HandleFunc("PUT "+options.BaseURL+"/member/{id}", wrapper.UpdateMember)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZb2/bthP+KgR/vxcbINju2gGd361dW6RYhyBpsReBEdDk2WYjkezx5MQI/N0HkrIs",
	"WbITr02WFXsTROKRvHueJ/dHueXSFs4aMOT5+JY7gaIAAoxPWoWfCrxE7Uhbw8dcaS8tqkut2A8OdSFw",
	"xa5gxeyMCVZAMQX8kWdcB1snaMEzbkQBfBxOyzjCl1IjKD4mLCHjXi6gEOEaWrlg5Qm1mfP1eh2MvbPG",
	"Q3TmlVBn8KUET+FJWkNg4q/CuVxLEfwbfvbBydvGsQ6tAySdDgFEW8VGUPiuQQHeizn0OZRt3tjpZ5DE",
	"ty8EoliF54O7t6Ff1IaTzqHBso34xwUwD7gEZNKWuWLGEiuNAvQkjGK0AIYJGaZKYGSZNkuRa8X8ypC4",
	"GQTXXlszy7X8GvAeLLqN99vwpsCCMHMgUJugBJNVDOxa0yLGLUtEMMQ8CYKgwQSGtyVKiHGfGAI0Ij+P",
	"CL4J/D9FCCqCwUhbBo9BMWFYaeDGgQwgSGuUDhsYLQQxh7AEExY0sRnags3KfKbzXJt5UxERgz8svbWl",
	"UU84cClM4H2m24IG1WRzvckX0aUPMdl0M9QZOAQPhmJkzcTEs52oJIIgUJeCegLLGrnu4LLR8qrXIN3q",
	"F9pdprUem5Qcexac1VVS7iyhMP0XehLTVnLrWOxmLE8gin0Blkb3A1M6tR+3HUHEAFtYNm6tYqmjzZqU",
	"VA5UYXXh3GGg5dakJ1snwbyOF3QV/nBka0MwBzyO7camHbobK/v4bpj0bbo/5fW2flJr1hqEtojeIWgX",
	"o/0snQokLfJPkdHHJOtf/Ze53ovnf0AeC2SP3Hdz1T7VH5W2egplxj3IEjWtzkO5q/pfEAj4/jq6O40P",
	"by0WIQXz939+5FVtDAelVV4fvCByqf5qM7PdivnmRoRei11bvPJOyOAjacrD3tdYeqEA2a+nJzzjS0Cf",
	"No0Go8GzAKF1YITTfMyfD0aD5wEgQYvo87Coa7SzqXFv35ySsWeCGbhmCAGW2MatHLCk3AGPV2Cs5ieq",
	"3vRhU9KrVuGVVaujGpz/I8z4mP9vuB2BhlV7MWyVinVbDmFw2R1Ofho9+8Z339UrXwvPfCkleD8r84yF",
	"SWCDYmqYoklVTmMb+GI02nd3HcywMWbFLb/cvaUeLdYZ//k+d/T15E3V8/FFS+8Xk/Uk474swrRZC2Db",
	"1JGY+9R7xheTcFYlveGtVuukuzBMdBX4W3wfFHhP9Z1BYZdb9TUn5ov+wLcmQ614CGVHOy+6bh2ielpS",
	"6JERmPbMWFapLsxICFSi+ftsv7h7Sz1MPBbbiaEDbGd8DtQ3BwQsjmD2HdA3pXX0CCnhvNZFvgrso4Yl",
	"pBGqqML8nrTwDuigEJwguehKoeom8xVLI8IRomg1ol8rj4cqVO1u+V716tHFGan5jqV5GuI7LM6yJ0t9",
	"OlaQT1uJT1qC1feBf0KCT7ORSmwdaqTiYeHwJK82uL9bKXKmYAm5dUX8DhttwwiEeTV4jIfDPNgtrKfx",
	"y9HLUVRgddPuiYlIhpBHomrl++2/ESrf1pP1XwEAAP//5qNezL0YAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
