//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerJwtScopes = "BearerJwt.Scopes"
)

// Member Representation of a member
type Member struct {
	CreatedAt      *time.Time     `json:"created_at,omitempty"`
	DiscordId      string         `json:"discordId"`
	DiscordNick    string         `json:"discordNick"`
	MembershipType MembershipType `json:"membershipType"`
	Name           string         `json:"name"`
	Points         *float32       `json:"points,omitempty"`
	Rank           *Rank          `json:"rank,omitempty"`
	Stab           *[]Stab        `json:"stab,omitempty"`
	SteamId        string         `json:"steamId"`
	UnitRole       *UnitRole      `json:"unitRole,omitempty"`
	UpdatedAt      *time.Time     `json:"updated_at,omitempty"`
}

// MemberCreate Representation of a member creation
type MemberCreate struct {
	DiscordId        string   `json:"discordId"`
	DiscordNick      string   `json:"discordNick"`
	MembershipTypeId int      `json:"membershipTypeId"`
	Name             string   `json:"name"`
	Points           *float32 `json:"points,omitempty"`
	RankLevel        *int     `json:"rankLevel,omitempty"`
	StabIds          *[]int   `json:"stabIds,omitempty"`
	SteamId          string   `json:"steamId"`
	UnitRoleId       *int     `json:"unitRoleId,omitempty"`
}

// MemberPartialUpdate Representation of a partial member update
type MemberPartialUpdate struct {
	DiscordId        *string  `json:"discordId,omitempty"`
	DiscordNick      *string  `json:"discordNick,omitempty"`
	MembershipTypeId *int     `json:"membershipTypeId,omitempty"`
	Name             *string  `json:"name,omitempty"`
	Points           *float32 `json:"points,omitempty"`
	RankLevel        *int     `json:"rankLevel,omitempty"`
	StabIds          *[]int   `json:"stabIds,omitempty"`
	SteamId          *string  `json:"steamId,omitempty"`
	UnitRoleId       *int     `json:"unitRoleId,omitempty"`
}

// MemberUpdate Representation of a member update
type MemberUpdate struct {
	DiscordId        string  `json:"discordId"`
	DiscordNick      string  `json:"discordNick"`
	MembershipTypeId int     `json:"membershipTypeId"`
	Name             string  `json:"name"`
	Points           float32 `json:"points"`
	RankLevel        int     `json:"rankLevel"`
	StabIds          []int   `json:"stabIds"`
	SteamId          string  `json:"steamId"`
	UnitRoleId       *int    `json:"unitRoleId,omitempty"`
}

// MembershipType defines model for Membership_Type.
type MembershipType struct {
	CreatedAt     time.Time `json:"created_at"`
	DiscordRoleId string    `json:"discordRoleId"`
	Id            int       `json:"id"`
	Name          string    `json:"name"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Rank defines model for Rank.
type Rank struct {
	CreatedAt time.Time `json:"created_at"`
	Level     int       `json:"level"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Stab defines model for Stab.
type Stab struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Id          int       `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Unit defines model for Unit.
type Unit struct {
	CreatedAt     time.Time `json:"created_at"`
	Description   string    `json:"description"`
	DiscordRoleId string    `json:"discord_role_id"`
	Id            int       `json:"id"`
	Name          string    `json:"name"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// UnitRole defines model for UnitRole.
type UnitRole struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Id          int       `json:"id"`
	Name        string    `json:"name"`
	Unit        Unit      `json:"unit"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Id defines model for id.
type Id = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Errors *[]struct {
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Message string `json:"message"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Message string `json:"message"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message string `json:"message"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message string `json:"message"`
}

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = MemberCreate

// PartialUpdateMemberJSONRequestBody defines body for PartialUpdateMember for application/json ContentType.
type PartialUpdateMemberJSONRequestBody = MemberPartialUpdate

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = MemberUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create member
	// (POST /member)
	CreateMember(w http.ResponseWriter, r *http.Request)
	// Delete member
	// (DELETE /member/{id})
	RemoveMember(w http.ResponseWriter, r *http.Request, id Id)
	// Get member
	// (GET /member/{id})
	GetMember(w http.ResponseWriter, r *http.Request, id Id)
	// Patch member
	// (PATCH /member/{id})
	PartialUpdateMember(w http.ResponseWriter, r *http.Request, id Id)
	// Update member
	// (PUT /member/{id})
	UpdateMember(w http.ResponseWriter, r *http.Request, id Id)
	// List members
	// (GET /members)
	ListMembers(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PartialUpdateMember operation middleware
func (siw *ServerInterfaceWrapper) PartialUpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PartialUpdateMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerJwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMembers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/member", wrapper.CreateMember)
	m.HandleFunc("DELETE "+options.BaseURL+"/member/{id}", wrapper.RemoveMember)
	m.HandleFunc("GET "+options.BaseURL+"/member/{id}", wrapper.GetMember)
	m.HandleFunc("PATCH "+options.BaseURL+"/member/{id}", wrapper.PartialUpdateMember)
	m.HandleFunc("PUT "+options.BaseURL+"/member/{id}", wrapper.UpdateMember)
	m.HandleFunc("GET "+options.BaseURL+"/members", wrapper.ListMembers)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7bOBN9FYLfd7GLVWM5SYvWd2m2LVI03SJJsRdBEDDi2GIjkSo5cmIEfpt9k32x",
	"BSlKsmTVP03iGEH3YlHbM+TMOYej0TB3NFJppiRINHRwRzOmWQoI2n0S3P6fg4m0yFAoSQeUCxMpzS8F",
	"J79lWqRMT8g1TIgaEkZSSK9A/04DKqxtxjCmAZUsBTqwqwVUw/dcaOB0gDqHgJoohpTZbXCSWSuDWsgR",
	"nU6n1thkShpwwbxl/AS+52DQfoqURJDunyzLEhExG1/vm7FB3s0sm2mVgUZRLAJaK58bQmrmDVIwho2g",
	"K6Cg/EZdfYMIaf0F05pN7OeF3nXq55Xhxdyi1rKJ+FkMxIAegyaRyhNOpEKSSw7aIJOcYAxEF8gQngNB",
	"RYQcs0RwYiYS2e2ODe1QyWEiovuA92jZldHX6V0BscJMAIGXSTES+RzIjcDY5R3lWoNEYpAhWA0WYBiV",
	"6whc3kcSQUuWnDoE31n+txECTzDISOU2YuCESZJLuM0gsiBESnJhHQjGDEmmYQzS/iCQDLVKyTBPhiJJ",
	"hBzNKsJh8Fnhe5VLvsWJR0xa3oeiKWjgs2xOy3rhQjp2xWa+Qp1ApsGARJfZbGGiQSurSAND4JfM4QG3",
	"zEqODuhuuPvyRb//Itwnu7uDvTeD/XAnfNV/1d/7IwxpQIdKp9aHcobwAkUKNGjjEpSl8og3Fw/79X8L",
	"3D6L6LrpeMxuyVvNhOzyKjI0scjO3E939P8ahnRA/9erS3zPw9c7rqwvnfm0rNKt/bp2ypTwT4vKtB+G",
	"laHMHdRWFkxeLwvkxNpYXpFdNcryIqdTa9xRfg0CS9twHyyBO5cCT1SyFLKvpZ31yfij6aZ1nhwtc/TW",
	"uc7KrKmdi44HVsH7oZP9OieHuJNirdpH6AlF3tqzXzkIiTAqNPg4qv4EY0iWb25FfcSb7cZijwdV9HJ8",
	"VtGa09V91PaFaRQs+erOzGqiywqXUnzFcfslvWcmvR/oZR2h/BLIr9pUJ11nVWF2v9JVN0hzDfFGWscO",
	"pGYR7vIUPyW8A3nz7z8aXYs8z9nmuh03I/BUNzEIZhFvxNRF34lvPTfJWbLawZsH/wMMNYinBz/xh8jj",
	"vw7ep7593+gZmX06zC5/BlEshe3byQFPhRQGddm8PtB5OX21TQdlBoj1aLPvNFtD24EcaTEcGvIugRQk",
	"LqiLl1olcNmijvb7j1IakyxmW8t2G5D1+S/ffbdCA+9zeY0kFUjO/jp8OA7tsj8or/4ELHvzfwrCXWz3",
	"PuW2U4Mo1wInpzYhP00HpkF/vHGpXLkP78swP/59Rv2kzS5U/FqHHCNmxTRPyKGa79PfFcCQG6WvTcYi",
	"l61AB9Whzg3joMnBlyMa0DFoUziFO+FO34KsMpAsE3RA93bCnT3byTGMXcy9tJr4Zaq4BmjuXMw1DGFE",
	"wg3RYE+GGwpPMiBFR7dD3RbF88C2Vt7puBwQ+sHjW8Una41Ll0/b/NRl2uQadQ7tq47dsP/Aey+bvN8w",
	"Q0weRWDMME8CwiSvUCzGr87Eq84NlffD8Ed7V8n0Zi5tnMub5S7VRcU0oC9X2aNrwj+rejo4b+j9/GJ6",
	"EVCTpynTk0oA9YgY2cgUk2z3xYVdy0uvdyf4tNBdAl3vqH+6760CV1TfCaRqXKtv9v7tvDvx2qQnOLWp",
	"tLSzPx/WIqqvciQYgwYiDJGKeNURVEQD5lr+PNv7y12qq4lNsV0wtIDtgI4Au6YPFos1mP0A+KC0hhso",
	"CaeVLpKJZV8LGENxIZP6NJ+TFj4ALhRCxjCK56XgB5rJxM+d1hBFYxZ6X3k81oOqObBd6Xm1cXE6ap6x",
	"NL/Y/BaLM++oUl/XFeR2K3GrJei77qeQ4HY2UgVbKzVSjrPO5+wnYZCwpLz7MXOKtQbH1W/36ptXumwu",
	"1dAegP9MQ23z8rETpsE3WM+toXYU1vTNy8CtZdcuqkxLACpiCeEwhkRlqfvjHmdr33N14t8/B71eYu1i",
	"ZXDwOnwdukLkd2qvWCBONCTuvFZyMvXfpvnYphfT/wIAAP//qxVAmxInAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
